name: Escalate to pSRE

on: [pull_request, workflow_dispatch]

jobs:
  file-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: 'rgraber@edx.org'
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Create ticket
        uses: atlassian/gajira-create@v3
        with:
          project: ARCHBOM
          issuetype: Task
          summary: rgraber is still testing things, ignore
          description: ignore me
          fields: { "labels": "dos-request" }
