name: Escalate to pSRE

on: [pull_request, workflow_dispatch]

jobs:
  file-jira:
    if: ${{ github.event.label.name == 'escalate-to-psre' }}
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: 'rgraber@edx.org'
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Create ticket
        uses: atlassian/gajira-create@v3
        with:
          project: ARCHBOM
          issuetype: Task
          summary: ${{ github.event.issue.title }}
          description: ${{ github.event.issue.body }}
          fields: { "labels": "dos-request" }
