name: Test-publish package to PyPI

on:
  pull_request:

jobs:
  test-publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pip
        run: pip install -r requirements/pip.txt

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI (test server)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_UPLOAD_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true

